filename_template = "names/{}{}.txt"

non_gendered_races = ["tavern", "goblin", "orc", "hillgiant"]
human_races = ["illuskan", "chondathan", "tethyrian", "damaran", "turami"]
race_vars={ # [text,  probablity]
            "elf":      [["F1", 1.],
                        ["F2M", 1.],
                        ["F2F", 1.],
                        ["L2",  1.],
                        ["L3",  1.],
                        ["T234",0.], #2
                        ["T234",0.],
                        ["T234",0.], #4
                        ["T5",  1.],
                        ["T6",  1.]],
            "halfling": [["F1", 1.],
                        ["F2M", 0.5],
                        ["F2F", 1.],
                        ["F3",  0.25],
                        ["L1",  0.15],
                        ["L2",  1.],
                        ["L3",  0.85]],
            "hillgiant":[["F1", 1.],
                        ["F2",  1.],
                        ["F3",  0.2]],
            "orc":      [["F1", 1.],
                        ["L1",  1.],
                        ["L2",  0.25],
                        ["L3",  1.]],
            "goblin":   [["F1", 1.],
                        ["F2",  0.75],
                        ["L1",  0.1]],
            "gnome":    [["F1", 1.],
                        ["F2M",0.25],
                        ["F2F",0.25],
                        ["L1",1.],
                        ["L2",1.]],
            "human":    [["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.95],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "illuskan": [["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.75],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "chondathan":[["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.75],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "tethyrian":[["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.75],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "damaran":  [["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.75],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "turami":   [["F1", 1.],
                        ["F2M", 0.75],
                        ["F2F", 0.75],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "dwarf":    [["F1", 1.],
                        ["F2M", 0.9],
                        ["F2F", 0.95],
                        ["L2", 1.],
                        ["L3", 0.95]],
            "tavern":   [["F1", 1.],
                        ["F2", 1.]],
            "tiefling": [["F1", 1.],
                        ["F2M", 1.],
                        ["F2F", 1.],
                        ["L2", 1.]],
}
race_name_spaces_dict = {"hillgiant": "hill giant"}

races = sorted(race_vars.keys())

surname_affix_list = ["Mac", "Mc", "Van", "Von", "O'"]
surname_affixes = [" {}".format(x) for x in surname_affix_list]